backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "./images" # Where media files will be stored
public_folder: "./images" # Where the media files can be accesed from the server

collections:
  - name: "recipe" 
    label: "Recipe" 
    folder: "content/recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Photo", name: "photo", widget: "image"}
      - label: "Recipe"
        name: "recipe"
        widget: "object"
        fields:
          - label: "Ingredients" 
            name: "ingredients" 
            widget: "list" 
            field: {label: "Ingredient", name: "ingredient", widget: "string"}
          - label: "Instructions"
            name: "instructions"
            widget: "text"
      
